services:
  fastapi:
    build: .
    container_name: fastapi_app
    command: uvicorn app.router:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./app:/app/app  # optional, allows live code reload in dev

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.worker.app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./app:/app/app

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
